### ISSUE TITLE
As a creative industry promoter, I want to have a web component to show information on a map within my homepage

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-generic-map#1]
- [x] Generate a web component to show stations on a map with vuejs
> This did not work out, due to issues integrating a CSS into a vuejs/web component wrapper
- [x] Generate a web component to show stations on a map with polymer lit-element
- [x] Retrieve data from the ODH mobility API v2 
- [x] Filter stations according to their station types
- [x] Document how to development and use it
- [x] Distribute it with jsdelivr
- [x] Create a demo app and integrate that into webcomponents.opendatahub.bz.it
- [x] Add a subpage on davinci.bz.it to demonstrate the new map widget for creative industries 
   - https://test.davinci.bz.it/en/work-package/10/creative-industries

**Comment by Piiit** [comment]
@ohnewein @rcavaliere Please test it on https://webcomponents.opendatahub.bz.it/generic-map/
As I wrote it already via email, the jsdelivr service may have the most up-to-date version not before tomorrow. Nevertheless, the creative industries example works already.

**Comment by ohnewein** [comment]
Creative Industries map looks good! Cool!

**Comment by ohnewein** [comment]
It looks as if all 3 maps on the website display the same dataset. Yesterday it visualized Creative Industries data, today I see eCharging stations and plugs on all 3 maps.

**Comment by ohnewein** [comment]
Hobs, I refreshed the website and now it looks as if the data has been changed to correct values. Maybe it has been just a caching problem on my side.
